INSERT INTO categories (
    id, name, system_key, type, sort_order, created_at, updated_at, created_by
)
SELECT gen_random_uuid(), v.name, v.system_key, v.type, v.sort_order,
       now(), now(), 'system'
FROM (VALUES
    ('Housing & Utilities',          'HOUSING_UTILITIES',          'EXPENSE', 10),
    ('Transportation',               'TRANSPORTATION',              'EXPENSE', 20),
    ('Food & Dining',                 'FOOD_DINING',                 'EXPENSE', 30),
    ('Healthcare',                    'HEALTHCARE',                  'EXPENSE', 40),
    ('Personal Care',                 'PERSONAL_CARE',               'EXPENSE', 50),
    ('Shopping',                      'SHOPPING',                    'EXPENSE', 60),
    ('Education',                     'EDUCATION',                   'EXPENSE', 70),
    ('Entertainment',                 'ENTERTAINMENT',               'EXPENSE', 80),
    ('Travel',                        'TRAVEL',                      'EXPENSE', 90),
    ('Insurance',                     'INSURANCE',                   'EXPENSE', 100),
    ('Debt Payments',                 'DEBT_PAYMENTS',               'EXPENSE', 110),
    ('Taxes & Fees',                  'TAXES_FEES',                  'EXPENSE', 120),
    ('Family & Dependents',           'FAMILY_DEPENDENTS',           'EXPENSE', 130),
    ('Pets',                          'PETS',                        'EXPENSE', 140),
    ('Gifts & Donations',             'GIFTS_DONATIONS',             'EXPENSE', 150),
    ('Business Expenses',             'BUSINESS_EXPENSES',           'EXPENSE', 160),
    ('Other Expenses',                'OTHER_EXPENSE',               'EXPENSE', 999),
    ('Salary & Wages',                'SALARY_WAGES',                'INCOME',  10),
    ('Self-Employment Income',        'SELF_EMPLOYMENT_INCOME',      'INCOME',  20),
    ('Investment Income',             'INVESTMENT_INCOME',           'INCOME',  30),
    ('Rental Income',                 'RENTAL_INCOME',               'INCOME',  40),
    ('Benefits & Pensions',           'BENEFITS_PENSIONS',           'INCOME',  50),
    ('Refunds & Reimbursements',      'REFUNDS_REIMBURSEMENTS',      'INCOME',  60),
    ('Other Income',                  'OTHER_INCOME',                'INCOME',  999)
) AS v(name, system_key, type, sort_order);

INSERT INTO sub_categories (
    id, name, system_key, sort_order, created_at, updated_at, created_by
)
SELECT gen_random_uuid(), v.name, v.system_key, v.sort_order,
       now(), now(), 'system'
FROM (VALUES
    ('Rent',                          'RENT',                          10),
    ('Mortgage',                      'MORTGAGE',                      20),
    ('Electricity',                   'ELECTRICITY',                   30),
    ('Water',                         'WATER',                         40),
    ('Gas',                           'GAS',                           50),
    ('Internet & Mobile',             'INTERNET_MOBILE',               60),
    ('Home Maintenance',              'HOME_MAINTENANCE',              70),
    ('Public Transit',                'PUBLIC_TRANSIT',                80),
    ('Fuel',                          'FUEL',                          90),
    ('Parking & Tolls',               'PARKING_TOLLS',                 100),
    ('Vehicle Maintenance',           'VEHICLE_MAINTENANCE',           110),
    ('Rideshare & Taxi',              'RIDESHARE_TAXI',                120),
    ('Groceries',                     'GROCERIES',                     130),
    ('Restaurants',                   'RESTAURANTS',                   140),
    ('Coffee & Snacks',               'COFFEE_SNACKS',                 150),
    ('Food Delivery',                 'FOOD_DELIVERY',                160),
    ('Medical',                       'MEDICAL',                       170),
    ('Pharmacy',                      'PHARMACY',                      180),
    ('Dental & Vision',               'DENTAL_VISION',                 190),
    ('Personal Care & Grooming',      'PERSONAL_CARE_GROOMING',       200),
    ('Clothing & Accessories',        'CLOTHING_ACCESSORIES',          210),
    ('Electronics',                   'ELECTRONICS',                   220),
    ('Household Items',               'HOUSEHOLD_ITEMS',               230),
    ('Tuition & Courses',             'TUITION_COURSES',               240),
    ('Books & Supplies',              'BOOKS_SUPPLIES',                250),
    ('Movies & Events',               'MOVIES_EVENTS',                 260),
    ('Hobbies & Recreation',          'HOBBIES_RECREATION',           270),
    ('Subscriptions',                 'SUBSCRIPTIONS',                 280),
    ('Flights',                       'FLIGHTS',                       290),
    ('Accommodation',                'ACCOMMODATION',                 300),
    ('Travel Activities',             'TRAVEL_ACTIVITIES',            310),
    ('Health Insurance',              'HEALTH_INSURANCE',             320),
    ('Auto Insurance',                'AUTO_INSURANCE',                330),
    ('Home & Renters Insurance',      'HOME_RENTERS_INSURANCE',       340),
    ('Life Insurance',                'LIFE_INSURANCE',                350),
    ('Personal Loan',                 'PERSONAL_LOAN',                 360),
    ('Credit Card Payment',           'CREDIT_CARD_PAYMENT',          370),
    ('Student Loan',                  'STUDENT_LOAN',                  380),
    ('Income Tax',                    'INCOME_TAX',                    390),
    ('Property Tax',                  'PROPERTY_TAX',                  400),
    ('Government Fees',               'GOVERNMENT_FEES',              410),
    ('Childcare',                     'CHILDCARE',                     420),
    ('School Expenses',               'SCHOOL_EXPENSES',               430),
    ('Pet Food & Supplies',           'PET_FOOD_SUPPLIES',            440),
    ('Veterinary Care',               'VETERINARY_CARE',              450),
    ('Charity & Donations',           'CHARITY_DONATIONS',            460),
    ('Gifts',                         'GIFTS',                         470),
    ('Business Supplies',             'BUSINESS_SUPPLIES',            480),
    ('Professional Services',         'PROFESSIONAL_SERVICES',        490),
    ('Salary',                        'SALARY',                        500),
    ('Bonus',                         'BONUS',                         510),
    ('Commission',                    'COMMISSION',                    520),
    ('Freelance',                     'FREELANCE',                     530),
    ('Business Revenue',              'BUSINESS_REVENUE',              540),
    ('Interest',                      'INTEREST',                      550),
    ('Dividends',                     'DIVIDENDS',                     560),
    ('Capital Gains',                 'CAPITAL_GAINS',                 570),
    ('Rent Received',                 'RENT_RECEIVED',                 580),
    ('Pension',                       'PENSION',                       590),
    ('Government Benefits',           'GOVERNMENT_BENEFITS',          600),
    ('Tax Refund',                    'TAX_REFUND',                    610),
    ('Expense Reimbursement',         'EXPENSE_REIMBURSEMENT',         620)
) AS v(name, system_key, sort_order);

INSERT INTO category_sub_categories (category_id, sub_category_id)
SELECT c.id, s.id
FROM (VALUES
    ('HOUSING_UTILITIES',     'RENT'),
    ('HOUSING_UTILITIES',     'MORTGAGE'),
    ('HOUSING_UTILITIES',     'ELECTRICITY'),
    ('HOUSING_UTILITIES',     'WATER'),
    ('HOUSING_UTILITIES',     'GAS'),
    ('HOUSING_UTILITIES',     'INTERNET_MOBILE'),
    ('HOUSING_UTILITIES',     'HOME_MAINTENANCE'),
    ('TRANSPORTATION',        'PUBLIC_TRANSIT'),
    ('TRANSPORTATION',        'FUEL'),
    ('TRANSPORTATION',        'PARKING_TOLLS'),
    ('TRANSPORTATION',        'VEHICLE_MAINTENANCE'),
    ('TRANSPORTATION',        'RIDESHARE_TAXI'),
    ('FOOD_DINING',           'GROCERIES'),
    ('FOOD_DINING',           'RESTAURANTS'),
    ('FOOD_DINING',           'COFFEE_SNACKS'),
    ('FOOD_DINING',           'FOOD_DELIVERY'),
    ('HEALTHCARE',            'MEDICAL'),
    ('HEALTHCARE',            'PHARMACY'),
    ('HEALTHCARE',            'DENTAL_VISION'),
    ('PERSONAL_CARE',         'PERSONAL_CARE_GROOMING'),
    ('SHOPPING',              'CLOTHING_ACCESSORIES'),
    ('SHOPPING',              'ELECTRONICS'),
    ('SHOPPING',              'HOUSEHOLD_ITEMS'),
    ('EDUCATION',             'TUITION_COURSES'),
    ('EDUCATION',             'BOOKS_SUPPLIES'),
    ('ENTERTAINMENT',         'MOVIES_EVENTS'),
    ('ENTERTAINMENT',         'HOBBIES_RECREATION'),
    ('ENTERTAINMENT',         'SUBSCRIPTIONS'),
    ('TRAVEL',                'FLIGHTS'),
    ('TRAVEL',                'ACCOMMODATION'),
    ('TRAVEL',                'TRAVEL_ACTIVITIES'),
    ('INSURANCE',             'HEALTH_INSURANCE'),
    ('INSURANCE',             'AUTO_INSURANCE'),
    ('INSURANCE',             'HOME_RENTERS_INSURANCE'),
    ('INSURANCE',             'LIFE_INSURANCE'),
    ('DEBT_PAYMENTS',         'PERSONAL_LOAN'),
    ('DEBT_PAYMENTS',         'CREDIT_CARD_PAYMENT'),
    ('DEBT_PAYMENTS',         'STUDENT_LOAN'),
    ('TAXES_FEES',            'INCOME_TAX'),
    ('TAXES_FEES',            'PROPERTY_TAX'),
    ('TAXES_FEES',            'GOVERNMENT_FEES'),
    ('FAMILY_DEPENDENTS',     'CHILDCARE'),
    ('FAMILY_DEPENDENTS',     'SCHOOL_EXPENSES'),
    ('PETS',                  'PET_FOOD_SUPPLIES'),
    ('PETS',                  'VETERINARY_CARE'),
    ('GIFTS_DONATIONS',       'CHARITY_DONATIONS'),
    ('GIFTS_DONATIONS',       'GIFTS'),
    ('BUSINESS_EXPENSES',     'BUSINESS_SUPPLIES'),
    ('BUSINESS_EXPENSES',     'PROFESSIONAL_SERVICES'),
    ('SALARY_WAGES',          'SALARY'),
    ('SALARY_WAGES',          'BONUS'),
    ('SALARY_WAGES',          'COMMISSION'),
    ('SELF_EMPLOYMENT_INCOME','FREELANCE'),
    ('SELF_EMPLOYMENT_INCOME','BUSINESS_REVENUE'),
    ('INVESTMENT_INCOME',     'INTEREST'),
    ('INVESTMENT_INCOME',     'DIVIDENDS'),
    ('INVESTMENT_INCOME',     'CAPITAL_GAINS'),
    ('RENTAL_INCOME',         'RENT_RECEIVED'),
    ('BENEFITS_PENSIONS',     'PENSION'),
    ('BENEFITS_PENSIONS',     'GOVERNMENT_BENEFITS'),
    ('REFUNDS_REIMBURSEMENTS','TAX_REFUND'),
    ('REFUNDS_REIMBURSEMENTS','EXPENSE_REIMBURSEMENT')
) AS v(category_key, sub_category_key)
JOIN categories c ON c.system_key = v.category_key
JOIN sub_categories s ON s.system_key = v.sub_category_key;
